<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js" integrity="sha256-xLD7nhI62fcsEZK2/v8LsBcb4lG7dgULkuXoXB/j91c=" crossorigin="anonymous"></script>
    
</head>
<body>
    <div class="info"></div>

    <script>
        const p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('resolve in promise');
            }, 300);
        });

        console.log(1);

        p.then(result => {
            console.log('first then', result);
            return new Promise((resolve, reject) => {
                console.log(2);
                setTimeout(() => {
                    resolve('resolve in first then in return in promise');
                }, 300);
            })
        })

        .then(a => {
            console.log(a);
            // a = 'resolve in first then in return in promise'
            // this .then() is executed because of the resolve in first then in return in promise
            throw new Error('error in second then');
        })
       

    </script>
</body>
</html>